In [1]:
import numpy as np
x = np.array([1.0,2.0,3.0])
type(x)

numpy.ndarray

In [2]:
y = np.array([2.0,3.0,4.0])
x + y


array([ 3.,  5.,  7.])

In [3]:
A = np.array([[1,2],[3,4]])

In [4]:
print(A)

[[1 2]
 [3 4]]


In [5]:
B = np.array([[3,0],[0,4]])

In [6]:
A + B

array([[4, 2],
       [3, 8]])

In [7]:
A * B

array([[ 3,  0],
       [ 0, 16]])

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20]])
A * B

array([[10, 40],
       [30, 80]])

In [9]:
X = np.array([[51,55],[14,19],[0,4]])
print(X) 

[[51 55]
 [14 19]
 [ 0  4]]


In [10]:
X[0][1]


55

In [12]:
import sys
for row in X:
    print(row)


[51 55]


SystemExit: 

To exit: use 'exit', 'quit', or Ctrl-D.


In [13]:
X = X.flatten()
X[np.array([0,2,4])]

array([51, 14,  0])